### ISSUE TITLE
Setup?

### ISSUE THREAD

**Issue by kirkins** [keatondunsford/feed#2]
I'm new to urbit and unsure about setting this up.

Do you put this into /home/web/ or does this run outside your urbit directory?

**Comment by keatondunsford** [comment]
@kirkins 
Hey! I published the setup instructions in a Fora post a few weeks ago. Just make sure to also read my *Update* comment immediately after the post and follow those steps too, or else you might break something if you're on an old ship.

Here's the link! Thanks for checking this out.

https://urbit.org/~~/fora/posts/~2017.4.12..21.14.00..fe17~/

The tutorial writeup will be coming out soon.

**Comment by kirkins** [comment]
Not sure if the site is down or a problem with my urbit setup.

![untitled](https://cloud.githubusercontent.com/assets/9503662/25773001/d64f91e4-3243-11e7-8fc1-abd0094d62ac.png)

**Comment by kirkins** [comment]
Got the page working. Going to try it out.
